project:
  type: book

book:
  title: "Guida di Frascati"
  author: "Claudio Comandini"
  date: "2024-01-24"
  page-navigation: true
  downloads: [pdf, epub]
  search: true
  repo-url: https://github.dev/scritture/guida-frascati/
  repo-actions: [edit]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - capitolo.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    documentclass: scrreprt
    fontfamily: libertinus
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  html:
    theme: cosmo
  epub:
    toc:
      true
    lang:
      it-IT
    date:
      "2024-01-24"
